name: E2eTestsWindos
 
on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''
 

  schedule:
    - cron: '0 3 * * *'

   
  pull_request:
    branches:
      - main    
 
 
jobs:
  Windows_Execution:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
 
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9
 
      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserName="edge" -Dheadless="false" -Dtest="${{github.event.inputs.testsPath}}" test
 
      
 
      - name: Generate Allure Report Single File
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Report 
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  Ubuntu_Excution:

    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Run Tests
        continue-on-error: true
        run: mvn -DBrowserName="chrome" -Dheadless=true -Dtest="${{ github.event.inputs.testsPath}}" test

      - name: Generate Allure Report Single File ubuntu
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_Report
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Headless_Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
